# Generated by Django 5.1 on 2024-09-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointmentmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], max_length=20, null=True),
        ),
    ]
