# Generated by Django 5.1 on 2024-09-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointmentmodel_status'),
        ('doctor', '0002_alter_doctormodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='refer_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refer_doctor_appointment', to='doctor.doctormodel'),
        ),
    ]
