# Generated by Django 5.1 on 2024-09-27 02:21

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointmentmodel_refer_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='referrence_no',
            field=models.CharField(blank=True, default=appointment.models.Appointmentmodel.create_new_ref_number, editable=False, max_length=10),
        ),
    ]
