# Generated by Django 5.1 on 2024-09-10 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.TextField(blank=True, default='nill', null=True)),
                ('license_no', models.IntegerField(blank=True, null=True)),
                ('organization_name', models.TextField(blank=True, default='nill', null=True)),
                ('location', models.TextField(blank=True, default='nill', null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('experiance', models.IntegerField(default=0, null=True)),
                ('available_status', models.TextField(null=True)),
                ('image', models.ImageField(default='default_images/default_avatar.png', upload_to='image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
