# Generated by Django 5.1 on 2024-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='experiance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='location',
            field=models.TextField(default='nill'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='organization_name',
            field=models.TextField(default='nill'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='license_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='speciality',
            field=models.TextField(default='nill'),
        ),
    ]
