# Generated by Django 5.1 on 2024-09-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctormodel_experiance_doctormodel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='experiance',
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='license_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='location',
            field=models.TextField(blank=True, default='nill', null=True),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='organization_name',
            field=models.TextField(blank=True, default='nill', null=True),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='speciality',
            field=models.TextField(blank=True, default='nill', null=True),
        ),
    ]
