# Generated by Django 5.1 on 2024-09-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='medical_historry',
            new_name='medical_history',
        ),
    ]
